_target_: models.tokenizer.Tokenizer

vocab_size: 1024
embed_dim: 1024
encoder:
  _target_: models.tokenizer.Encoder
  config:
    _target_: models.tokenizer.EncoderDecoderConfig
    resolution: 128
    in_channels: 1
    z_channels: 1024
    ch: 128
    ch_mult: [1, 1, 2, 2, 4]
    num_res_blocks: 2
    attn_resolutions: [8]
    out_ch: 1
    dropout: 0.0
decoder:
  _target_: models.tokenizer.Decoder
  config: ${..encoder.config}